services:
    catalogdb:
        image: postgres

    catalog.api:
      image: ${DOCKER_REGISTRY-}catalogapi
      build:
        context: C:\Users\josem\Desktop\Repositories\Microservices-E-Commerce-App\EShop-Microservices\src\Services\Catalog\Catalog.API
        dockerfile: Dockerfile
volumes:
    postgres_catalog:
    